# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af24d6c305e755a60e304c01a8bde8e6145b07ce00825e4dcbb169f78aadb7a99e1cb75c2b89261184a24c17d72633acfd8fed8fe1ccddbd65d4e5d918e4795b
  CONSUMER_KEY: 0gz1kVR7YRSKCSTYjpJDil1QN
  CONSUMER_SECRET: yoMIxQWgpq5QuE3My96U37szRQgSNR9n1BXKK5SRQtG0mftXx8
  YOUR_ACCESS_TOKEN: 747481216715194372-ki4YkyY03fU3LDMBdsA17aITIqefUmC
  YOUR_ACCESS_SECRET: zdUjnJIBUu43NWHnbalR6ZE6kY8mpCVEBqMktsv16Vque

test:
  secret_key_base: 5d1e85abea1bd5092893d04fb3959b845fe19fc624415a7ecc81b77d73a5f12d9b8c3f659497a507cbb9f4f438f42b67e680dd4f07ccf9e3e9d3cbc7116269b8
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  CONSUMER_KEY: <%= ENV['CONSUMER_KEY'] %>
  CONSUMER_SECRET: <%= ENV['CONSUMER_SECRET'] %>
  YOUR_ACCESS_TOKEN: <%= ENV['YOUR_ACCESS_TOKEN'] %>
  YOUR_ACCESS_SECRET: <%= ENV['YOUR_ACCESS_SECRET'] %>
